SELECT
  MAX(PLAYER_NAME) AS name,
  ROUND(SUM(PTS) / SUM(CASE WHEN MIN > 0 THEN 1 ELSE 0 END), 2) AS ppg
FROM
  {{ ref("final_stats_player") }}
WHERE
  TEAM_ABBREVIATION = "BOS"
GROUP BY
  PLAYER_ID
ORDER BY
  2 DESC
LIMIT 15